# Windowsで使用する場合はDockerfileのディレクトリの
# スラッシュをバックスラッシュに変更すること。
# build: ./Dockerfile ->　build: .\Dockerfile
# comandはSMTP認証の有無で選択

version: '3'
services:
  maildev-maildev:
    container_name: maildev-maildev
    build: ./Dockerfile
    restart: always
    environment:
      - TZ=Asia/Tokyo
    ports:
      - "1080:1080"
      - "1025:1025"
    #command: /bin/maildev
    command: bin/maildev --incoming-user testsender01 --incoming-pass testsender01